# Generated by Django 6.0.3 on 2026-03-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Licitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=100)),
                ('orgao', models.CharField(max_length=255)),
                ('valor', models.FloatField()),
                ('data', models.DateField()),
                ('empresa_vencedora', models.CharField(max_length=255)),
            ],
        ),
    ]
